server:
    port: 8080
spring:
  application:
    name: gatway
  cloud:
    nacos:
      server-addr: ${hm.nacos.host}
    gateway:
      routes:
      - id: item-service
        uri: lb://item-service
        predicates:
          - Path=/items/**,/search/**
      - id: cart-service
        uri: lb://cart-service
        predicates:
          - Path=/carts/**
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/addresses/**,/users/**
      - id: pay-service
        uri: lb://pay-service
        predicates:
          - Path=/pay-orders/**        
      - id: trade-service
        uri: lb://trade-service
        predicates:
          - Path=/orders/**   
    #  全部都加上过滤器
    # default-filters:
      default-filters:
        - AddRequestHeader=truth,anyone long-press like button will be ring
        # - PrintAny=1,2,3
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi